const quizData = [
    { category: "Fruit", word: "Banana", answer: "Vahllei Pallam" },
    { category: "Fruit", word: "Apple", answer: "Saebbu Pallam" },
    { category: "Fruit", word: "Mango", answer: "Maambalam" },
    { category: "Fruit", word: "Papaya", answer: "Pabali Pallam" },
    { category: "Fruit", word: "Guava", answer: "Koyya Pallam" },
    { category: "Fruit", word: "Grapes", answer: "Dhrakshai" },
    { category: "Fruit", word: "Pineapple", answer: "Annassee Pallam" },
    { category: "Fruit", word: "Orange", answer: "Aranssee Pallam" },
    { category: "Fruit", word: "Watermelon", answer: "Tharbujam" },
    { category: "Fruit", word: "Pomegranate", answer: "Madhulai" },
    { category: "Vehicle", word: "Car", answer: "Motaar Varhunum" },
    { category: "Vehicle", word: "Lorry", answer: "Lorry" },
    { category: "Vehicle", word: "Bike", answer: "Thuvee Chakara Vandee" },
    { category: "Vehicle", word: "Motorbike", answer: "Motaar Vandee" },
    { category: "Vehicle", word: "Van", answer: "Van" },
    { category: "Vehicle", word: "Jeep", answer: "Jeep" },
    { category: "Vehicle", word: "Plane", answer: "Ah-ha-ya Vimarnum" },
    { category: "Vehicle", word: "Helicopter", answer: "Helicopter" },
    { category: "Vehicle", word: "Taxi", answer: "Motaar Varhunum" },
    { category: "Vehicle", word: "Bus", answer: "Bus Vandee" },
    { category: "Vehicle", word: "Boat", answer: "Padahu" },
    { category: "Vehicle", word: "Ship", answer: "Cupal" },
    { category: "Vehicle", word: "Train", answer: "Puhai Vandee" },
    { category: "Days", word: "Monday", answer: "Thingul Kilumai" },
    { category: "Days", word: "Tuesday", answer: "Sevai Kilumai" },
    { category: "Days", word: "Wednesday", answer: "Pudhan Kilumai" },
    { category: "Days", word: "Thursday", answer: "Vee-yaarla Kilumai" },
    { category: "Days", word: "Friday", answer: "Vuhllee Kilumai" },
    { category: "Days", word: "Saturday", answer: "Sanny Kilumai" },
    { category: "Days", word: "Sunday", answer: "Nyaitru Kilumai" },
    { category: "Months", word: "January", answer: "Thigh Marthum" },
    { category: "Months", word: "February", answer: "Marsee Marthum" },
    { category: "Months", word: "March", answer: "Pungoonee Marthum" },
    { category: "Months", word: "April", answer: "Sittheerai Marthum" },
    { category: "Months", word: "May", answer: "Whycarsee Marthum" },
    { category: "Months", word: "June", answer: "Ahnee Marthum" },
    { category: "Months", word: "July", answer: "Ardee Marthum" },
    { category: "Months", word: "August", answer: "Arvanee Marthum" },
    { category: "Months", word: "September", answer: "Purrattarthee Marthum" },
    { category: "Months", word: "October", answer: "Eyepersee Marthum" },
    { category: "Months", word: "November", answer: "Carteehai Marthum" },
    { category: "Months", word: "December", answer: "Marrhullee Marthum" },
    { category: "Colours", word: "Blue", answer: "Neelam" },
    { category: "Colours", word: "Green", answer: "Patchei" },
    { category: "Colours", word: "Red", answer: "Sivapu" },
    { category: "Colours", word: "Yellow", answer: "Munjal" },
    { category: "Colours", word: "Orange", answer: "Sem Munjal" },
    { category: "Colours", word: "Black", answer: "Kahrrupu" },
    { category: "Colours", word: "White", answer: "Vellei" },
    { category: "Colours", word: "Purple", answer: "Oohtha" },
    { category: "Colours", word: "Pink", answer: "ellam Sivapu" },
    { category: "Colours", word: "Brown", answer: "Cuhbeelam" },
    { category: "Colours", word: "Grey", answer: "Saambal" },
    { category: "Colours", word: "Gold", answer: "Thungam" },
    { category: "Colours", word: "Silver", answer: "Vuhlee" },
    { category: "Directions", word: "Right", answer: "Vahlethu" },
    { category: "Directions", word: "Left", answer: "Edathu" },
    { category: "Directions", word: "Up", answer: "Maylay" },
    { category: "Directions", word: "Down", answer: "Kuhlay" },
    { category: "Directions", word: "North", answer: "VadakkuTissehai" },
    { category: "Directions", word: "East", answer: "cUHllakkuTissehai" },
    { category: "Directions", word: "North East", answer: "VadaCuhlakku Tissehai" },
    { category: "Directions", word: "South", answer: "ThetkuTissehai" },
    { category: "Directions", word: "South East", answer: "ThenCuhlakku Tissehai" },
    { category: "Directions", word: "West", answer: "MaytkuTissehai" },
    { category: "Directions", word: "South West", answer: "ThenMaytku Tissehai" },
    { category: "Directions", word: "North West", answer: "VadaMaytku Tissehai" },
    { category: "Directions", word: "Behind", answer: "Pinaal" },
    { category: "Directions", word: "In front", answer: "Munaal" },
    { category: "Directions", word: "In", answer: "ULlay" },
    { category: "Directions", word: "Out", answer: "VuhLleeyay" },
    { category: "Body Parts", word: "Head", answer: "Thalay" },
    { category: "Body Parts", word: "Forehead", answer: "Netree" },
    { category: "Body Parts", word: "Face", answer: "Muham" },
    { category: "Body Parts", word: "Cheeks", answer: "Kuhnam" },
    { category: "Body Parts", word: "Lips", answer: "Uthadu" },
    { category: "Body Parts", word: "Tongue", answer: "Naakku" },
    { category: "Body Parts", word: "Teeth", answer: "Pal" },
    { category: "Body Parts", word: "Neck", answer: "KuhLootthu" },
    { category: "Body Parts", word: "Nose", answer: "Mookku" },
    { category: "Body Parts", word: "Eyes", answer: "Kungal" },
    { category: "Body Parts", word: "Ears", answer: "Carthuhal" },
    { category: "Body Parts", word: "Hair", answer: "Mudi" },
    { category: "Body Parts", word: "Hands", answer: "Kai" },
    { category: "Body Parts", word: "Shoulder", answer: "ThaLl" },
    { category: "Body Parts", word: "Palms", answer: "Ullum Kai" },
    { category: "Body Parts", word: "Chest", answer: "Nenju" },
    { category: "Body Parts", word: "Back", answer: "Moothuhu" },
    { category: "Body Parts", word: "Stomach", answer: "Vyroo" },
    { category: "Body Parts", word: "Legs", answer: "Kaalhal" },
    { category: "Body Parts", word: "Thigh", answer: "Thodei" },
    { category: "Body Parts", word: "Knee", answer: "Mullum Kaal" },
    { category: "Body Parts", word: "Foot", answer: "Parthum" },
    { category: "Body Parts", word: "Skin", answer: "Thall" },
    { category: "Body Parts", word: "Fingers", answer: "Kai Virrulhal" },
    { category: "Body Parts", word: "Toes", answer: "Kaal Virrulhal" },
    { category: "Body Parts", word: "Nail", answer: "Nahum" }
  ];
  
