const quizData = [
    //Fruits category
    { category: "Fruit", word: "Fruit", answer: "Pallam" },
    { category: "Fruit", word: "Pumpkin", answer: "Poosaneekai" },
    { category: "Fruit", word: "Banana", answer: "Vahllei Pallam" },
    { category: "Fruit", word: "Mango", answer: "Maam Pallam" },
    { category: "Fruit", word: "Papaya", answer: "Papasi Pallam" },
    { category: "Fruit", word: "Grapes", answer: "Dhrakshai" },
    { category: "Fruit", word: "Pineapple", answer: "Annahsi Pallam" },
    { category: "Fruit", word: "Orange", answer: "Thowdam Pallam" },
    { category: "Fruit", word: "Watermelon", answer: "Tharrpoosanee Pallam" },
    { category: "Fruit", word: "Melon", answer: "Velleri Pallam" },
    { category: "Fruit", word: "Tomato", answer: "Thuckahlee Pallam" },
    { category: "Fruit", word: "Pomegranate", answer: "Mathoolam Pallam" },
    //Vehicle category
    { category: "Vehicle", word: "Vehicle", answer: "Vandi" },
    { category: "Vehicle", word: "Car", answer: "Motaar Varhunum" },
    { category: "Vehicle", word: "Bike", answer: "Thuvee Chakara Vandee" },
    { category: "Vehicle", word: "Motorbike", answer: "Motaar Vandee" },
    { category: "Vehicle", word: "Plane", answer: "Ah-ha-ya Vimarnum" },
    { category: "Vehicle", word: "Taxi", answer: "Motaar Varhunum" },
    { category: "Vehicle", word: "Bus", answer: "Bus Vandee" },
    { category: "Vehicle", word: "Boat", answer: "Padahu" },
    { category: "Vehicle", word: "Ship", answer: "Cupal" },
    { category: "Vehicle", word: "Train", answer: "Puhai Vandee" },
    //Days category
    { category: "Days", word: "Day", answer: "Naal" },
    { category: "Days", word: "Monday", answer: "Thingut Kilumai" },
    { category: "Days", word: "Tuesday", answer: "Sevai Kilumai" },
    { category: "Days", word: "Wednesday", answer: "Pudhan Kilumai" },
    { category: "Days", word: "Thursday", answer: "Vee-yaarla Kilumai" },
    { category: "Days", word: "Friday", answer: "Vuhllee Kilumai" },
    { category: "Days", word: "Saturday", answer: "Sanny Kilumai" },
    { category: "Days", word: "Sunday", answer: "Nyaitru Kilumai" },
    //Months category
    { category: "Months", word: "Month", answer: "Marthum" },
    { category: "Months", word: "Year", answer: "Varrudum" },
    { category: "Months", word: "January", answer: "Thigh Marthum" },
    { category: "Months", word: "February", answer: "Marsee Marthum" },
    { category: "Months", word: "March", answer: "Pungoonee Marthum" },
    { category: "Months", word: "April", answer: "Sittheerai Marthum" },
    { category: "Months", word: "May", answer: "Whycarsee Marthum" },
    { category: "Months", word: "June", answer: "Ahnee Marthum" },
    { category: "Months", word: "July", answer: "Ardee Marthum" },
    { category: "Months", word: "August", answer: "Arvanee Marthum" },
    { category: "Months", word: "September", answer: "Purrattarthee Marthum" },
    { category: "Months", word: "October", answer: "Eyepersee Marthum" },
    { category: "Months", word: "November", answer: "Carteehai Marthum" },
    { category: "Months", word: "December", answer: "Marrhullee Marthum" },
    //Colours category
    { category: "Colours", word: "Blue", answer: "Neelam" },
    { category: "Colours", word: "Green", answer: "Patchei" },
    { category: "Colours", word: "Red", answer: "Sivapu" },
    { category: "Colours", word: "Yellow", answer: "Munjal" },
    { category: "Colours", word: "Orange", answer: "Sem Munjal" },
    { category: "Colours", word: "Black", answer: "Kahrrupu" },
    { category: "Colours", word: "White", answer: "Vellei" },
    { category: "Colours", word: "Purple", answer: "Oohtha" },
    { category: "Colours", word: "Pink", answer: "ellam Sivapu" },
    { category: "Colours", word: "Brown", answer: "Cuhbeelam" },
    { category: "Colours", word: "Grey", answer: "Saambal" },
    { category: "Colours", word: "Gold", answer: "Thungam" },
    { category: "Colours", word: "Silver", answer: "Vuhlee" },
    //Directions category
    { category: "Directions", word: "Right", answer: "Vahlethu" },
    { category: "Directions", word: "Left", answer: "Edathu" },
    { category: "Directions", word: "Up", answer: "Maylay" },
    { category: "Directions", word: "Down", answer: "Kuhlay" },
    { category: "Directions", word: "North", answer: "VadakkuTissehai" },
    { category: "Directions", word: "East", answer: "cUHllakkuTissehai" },
    { category: "Directions", word: "North East", answer: "VadaCuhlakku Tissehai" },
    { category: "Directions", word: "South", answer: "ThetkuTissehai" },
    { category: "Directions", word: "South East", answer: "ThenCuhlakku Tissehai" },
    { category: "Directions", word: "West", answer: "MaytkuTissehai" },
    { category: "Directions", word: "South West", answer: "ThenMaytku Tissehai" },
    { category: "Directions", word: "North West", answer: "VadaMaytku Tissehai" },
    { category: "Directions", word: "Behind", answer: "Pinaal" },
    { category: "Directions", word: "In front", answer: "Munaal" },
    { category: "Directions", word: "In", answer: "ULlay" },
    { category: "Directions", word: "Out", answer: "VuhLleeyay" },
    //Body parts category
    { category: "Body Parts", word: "Head", answer: "Thalay" },
    { category: "Body Parts", word: "Forehead", answer: "Netree" },
    { category: "Body Parts", word: "Face", answer: "Muham" },
    { category: "Body Parts", word: "Cheeks", answer: "Kuhnam" },
    { category: "Body Parts", word: "Lips", answer: "Uthadu" },
    { category: "Body Parts", word: "Tongue", answer: "Naakku" },
    { category: "Body Parts", word: "Teeth", answer: "Pal" },
    { category: "Body Parts", word: "Neck", answer: "KuhLootthu" },
    { category: "Body Parts", word: "Nose", answer: "Mookku" },
    { category: "Body Parts", word: "Eyes", answer: "Kungal" },
    { category: "Body Parts", word: "Ears", answer: "Carthuhal" },
    { category: "Body Parts", word: "Hair", answer: "Mudi" },
    { category: "Body Parts", word: "Hands", answer: "Kai" },
    { category: "Body Parts", word: "Shoulder", answer: "ThaLl" },
    { category: "Body Parts", word: "Palms", answer: "Ullum Kai" },
    { category: "Body Parts", word: "Chest", answer: "Nenju" },
    { category: "Body Parts", word: "Back", answer: "Moothuhu" },
    { category: "Body Parts", word: "Stomach", answer: "Vyroo" },
    { category: "Body Parts", word: "Legs", answer: "Kaalhal" },
    { category: "Body Parts", word: "Thigh", answer: "Thodei" },
    { category: "Body Parts", word: "Knee", answer: "Mullum Kaal" },
    { category: "Body Parts", word: "Foot", answer: "Parthum" },
    { category: "Body Parts", word: "Skin", answer: "Thall" },
    { category: "Body Parts", word: "Fingers", answer: "Kai Virrulhal" },
    { category: "Body Parts", word: "Toes", answer: "Kaal Virrulhal" },
    { category: "Body Parts", word: "Nail", answer: "Nahum" },
    //Numbers category
    { category: "Numbers", word: "One", answer: "Ondu" },
    { category: "Numbers", word: "First", answer: "Muthal arm Thiherthee" },
    { category: "Numbers", word: "Two", answer: "Rendu" },
    { category: "Numbers", word: "Second", answer: "Rendu arm (ignore the u in rendu)Thiherthee" },
    { category: "Numbers", word: "Three", answer: "Moondru (Moondu)" },
    { category: "Numbers", word: "Third", answer: "Moondr arm Thiherthee" },
    { category: "Numbers", word: "Four", answer: "Nangoo (Nalu)" },
    { category: "Numbers", word: "Fourth", answer: "Nang arm Thiherthee" },
    { category: "Numbers", word: "Five", answer: "Eyenthu (Anju)" },
    { category: "Numbers", word: "Fifth", answer: "Eyeth arm Thiherthee" },
    { category: "Numbers", word: "Six", answer: "Arru" },
    { category: "Numbers", word: "Sixth", answer: "Arr arm Thiherthee" },
    { category: "Numbers", word: "Seven", answer: "Erlu" },
    { category: "Numbers", word: "Seventh", answer: "Erl arm Thiherthee" },
    { category: "Numbers", word: "Eight", answer: "Ettwo" },
    { category: "Numbers", word: "Eighth", answer: "Uttw arm Thiherthee" },
    { category: "Numbers", word: "Nine", answer: "Onbathu" },
    { category: "Numbers", word: "Ninth", answer: "Onbath arm Thiherthee" },
    { category: "Numbers", word: "Ten", answer: "Patthu" },
    { category: "Numbers", word: "Tenth", answer: "Patth arm Thiherthee" },
    { category: "Numbers", word: "Eleven", answer: "Pathin Ondru" },
    { category: "Numbers", word: "Eleventh", answer: "Pathin Ondr arm Thiherthee" },
    { category: "Numbers", word: "Twelve", answer: "Pan Rrendu (slang: Panendu)" },
    { category: "Numbers", word: "Twelveth", answer: "Pan Rrend arm Thiherthee" },
    { category: "Numbers", word: "Thirteen", answer: "Pathin Moondu (Pathimoondu)" },
    { category: "Numbers", word: "Thirteenth", answer: "Pathimoond arm Thiherthee" },
    { category: "Numbers", word: "Fourteen", answer: "Pathin Nalu (Pathinalu)" },
    { category: "Numbers", word: "Fourteenth", answer: "Pathinal arm Thiherthee" },
    { category: "Numbers", word: "Fifteen", answer: "Pathin Anju (pathinanju)" },
    { category: "Numbers", word: "Fifteenth", answer: "Pathinanj arm Thiherthee" },
    { category: "Numbers", word: "Sixteen", answer: "Pathin Ahru (pathinahru)" },
    { category: "Numbers", word: "Sixteenth", answer: "Pathinahr arm Thiherthee" },
    { category: "Numbers", word: "Seventeen", answer: "Pathin Erlu (pathinerlu)" },
    { category: "Numbers", word: "Seventeenth", answer: "Pathinerl arm Thiherthee" },
    { category: "Numbers", word: "Eighteen", answer: "Pathin Ettwo (pathinuttwo)" },
    { category: "Numbers", word: "Eighteenth", answer: "Pathinuttw arm Thiherthee" },
    { category: "Numbers", word: "Nineteen", answer: "Pathin Onbathu (Paththonbathu)" },
    { category: "Numbers", word: "Nineteenth", answer: "Paththonbath arm Thiherthee" },
    { category: "Numbers", word: "Twenty", answer: "Irruverthu" },
    { category: "Numbers", word: "Twentieth", answer: "Irruverth arm Thiherthee" },
    { category: "Numbers", word: "Twenty One", answer: "Irruverthee Ondru" },
    { category: "Numbers", word: "Twenty first", answer: "Irruverthee Ondr arm Thiherthee" },
    { category: "Numbers", word: "Twenty Two", answer: "Irruverthee Rrendu" },
    { category: "Numbers", word: "Twenty Three", answer: "Irruverthee Moondu" },
    { category: "Numbers", word: "Twenty Four", answer: "Irruverthee Nalu" },
    { category: "Numbers", word: "Twenty Five", answer: "Irruverthee Anju" },
    { category: "Numbers", word: "Twenty Six", answer: "Irruverthee Ahru" },
    { category: "Numbers", word: "Twenty Seven", answer: "Irruverthee Ehlu" },
    { category: "Numbers", word: "Twenty Eight", answer: "Irruverthee Ettwo" },
    { category: "Numbers", word: "Twenty Nine", answer: "Irruverthee Ombathu" },
    { category: "Numbers", word: "Thirty", answer: "MooPpathu" },
    { category: "Numbers", word: "Thirtieth", answer: "Mooppath arm Thiherthee" },
    { category: "Numbers", word: "Thirty one", answer: "MooPpaththee Ondru" },
    { category: "Numbers", word: "Thirty first", answer: "MooPpaththee Ondr arm Thirherthee" },
    { category: "Numbers", word: "Forty", answer: "NaaPpathu" },
    { category: "Numbers", word: "Forty One", answer: "NaaPpaththee Ondru" },
    { category: "Numbers", word: "Fifty", answer: "Eyempathu" },
    { category: "Numbers", word: "Fifty One", answer: "Eyempaththee Ondru" },
    { category: "Numbers", word: "Sixty", answer: "Arruvathu" },
    { category: "Numbers", word: "Sixty One", answer: "Arruvaththee Ondru" },
    { category: "Numbers", word: "Seventy", answer: "Elluvathu" },
    { category: "Numbers", word: "Seventy One", answer: "Elluvaththee Ondru" },
    { category: "Numbers", word: "Eighty", answer: "Enbathu" },
    { category: "Numbers", word: "Eighty One", answer: "Enbaththee Ondru" },
    { category: "Numbers", word: "Ninety", answer: "ThoNnooru" },
    { category: "Numbers", word: "Ninety One", answer: "ThoNnootee Ondru" },
    { category: "Numbers", word: "Hundred", answer: "Noohroo" },
    { category: "Numbers", word: "Hundred and One", answer: "Noohtee Ondru" },
    { category: "Numbers", word: "154", answer: "Noohtee Eyempaththee Nalu" },
    { category: "Numbers", word: "One Thousand", answer: "Ahyirum" },
    { category: "Numbers", word: "Two Thousand", answer: "Rendu Ahyirum (Rend Ahyirum)" },
    { category: "Numbers", word: "Three Thousand", answer: "Moondu Ahyirum (Moond Ahyirum)" },
    { category: "Numbers", word: "One Thousand and One", answer: "Ahyiraththu Ondru" },
    { category: "Numbers", word: "One Thousand and Two", answer: "Ahyiraththu Rendu" },
    //Vegetables category
    { category: "Vegetables", word: "Vegetable", answer: "Marracurry / Kaicurry" },
    { category: "Vegetables", word: "Cucumber", answer: "Vellerikai" },
    { category: "Vegetables", word: "Chilli", answer: "Mellerhai" },
    { category: "Vegetables", word: "Green Chilli", answer: "Pachei Mellerhai" },
    { category: "Vegetables", word: "Red Chilli", answer: "Sivapu Mellerhai" },
    { category: "Vegetables", word: "Dried Chilli", answer: "Kinduh Mellerhai" },
    { category: "Vegetables", word: "Spinach", answer: "Puhssalee" },
    { category: "Vegetables", word: "Leafy Vegetables", answer: "Keerai" },
    { category: "Vegetables", word: "Green Beans", answer: "Bounjeekai" },
    { category: "Vegetables", word: "Flat Beans", answer: "Averraikai" },
    { category: "Vegetables", word: "Long Beans", answer: "Payerthungai" },
    { category: "Vegetables", word: "Aubergine", answer: "Kuththereekai" },
    { category: "Vegetables", word: "Potato", answer: "Urralei Killungoo" },
    { category: "Vegetables", word: "Yam", answer: "Killungoo" },
    { category: "Vegetables", word: "Sweet Potato", answer: "Vuththaalei Killungoo" },
    { category: "Vegetables", word: "Tapioca", answer: "Marravullee Killungoo" },
    { category: "Vegetables", word: "Onion", answer: "Venguyam" },
    { category: "Vegetables", word: "Garlic", answer: "Poondoo" },
    { category: "Vegetables", word: "Ginger", answer: "Injee" },
    { category: "Vegetables", word: "Cabbage", answer: "Gowa" },
    { category: "Vegetables", word: "Corn", answer: "Sohlam" },
    { category: "Vegetables", word: "Bittergourd", answer: "Parvakkai" },
    { category: "Vegetables", word: "Drumstick", answer: "Moorungakai" },
    { category: "Vegetables", word: "Okra", answer: "Vendikai" },
    //Meats category
    { category: "Meats", word: "Meat", answer: "(E)rraichee" },
    { category: "Meats", word: "Mutton (Goat/Lamb)", answer: "Artu Erraichee" },
    { category: "Meats", word: "Beef (Cow)", answer: "Martu Erraichee" },
    { category: "Meats", word: "Chicken (Hen)", answer: "Cawli Erraichee" },
    { category: "Meats", word: "Pork (Pig)", answer: "Pundri Erraichee" },
    { category: "Meats", word: "Turkey", answer: "Vaancawli Erraichee" },
    { category: "Meats", word: "Duck", answer: "Vahtu Erraichee" },
    //Other Foods category
    { category: "Other Foods", word: "Fish", answer: "Meen" },
    { category: "Other Foods", word: "Shrimp / Prawn", answer: "Raal" },
    { category: "Other Foods", word: "Crab", answer: "Nandu" },
    { category: "Other Foods", word: "Egg", answer: "Moott-tei" },
    { category: "Other Foods", word: "Milk", answer: "Paal" },
    { category: "Other Foods", word: "Tea", answer: "Theineer" },
    { category: "Other Foods", word: "Milk tea", answer: "Theithanee" },
    { category: "Other Foods", word: "Coffee", answer: "Copee" },
    { category: "Other Foods", word: "Oyster", answer: "Muttee" },
    { category: "Other Foods", word: "Squid", answer: "Mutti" },
    { category: "Other Foods", word: "Cuttlefish", answer: "Kanuhvai" },
    { category: "Other Foods", word: "Any food that is fried", answer: "Poreeyal" },
    //Animals category
    { category: "Animals", word: "Animal", answer: "Mirruham" },
    { category: "Animals", word: "Cow", answer: "Mardu" },
    { category: "Animals", word: "Sheep", answer: "Sem-meree Ardu" },
    { category: "Animals", word: "Goat", answer: "Ardu" },
    { category: "Animals", word: "Dog", answer: "Nai" },
    { category: "Animals", word: "Cat", answer: "Poonai" },
    { category: "Animals", word: "Pig", answer: "Pundree" },
    { category: "Animals", word: "Horse", answer: "Cootheerai" },
    { category: "Animals", word: "Monkey", answer: "Coorungoo" },
    { category: "Animals", word: "Giraffe", answer: "Ottahachivingee" },
    { category: "Animals", word: "Zebra", answer: "VahreecCootheerai" },
    { category: "Animals", word: "Deer", answer: "Maan" },
    { category: "Animals", word: "Lion", answer: "SingGam" },
    { category: "Animals", word: "Tiger", answer: "Pullee" },
    { category: "Animals", word: "Elephant", answer: "Yahnei" },
    { category: "Animals", word: "Leopard", answer: "Sirootthei" },
    { category: "Animals", word: "Donkey", answer: "Kaloothei" },
    { category: "Animals", word: "Rabbit", answer: "Mouyall" },
    { category: "Animals", word: "Fox", answer: "Naree" },
    { category: "Animals", word: "Bull", answer: "Eroomei Mardu" },
    { category: "Animals", word: "Beaver", answer: "Neerrnai" },
    { category: "Animals", word: "Wolf", answer: "Ohnai" },
    { category: "Animals", word: "Wild Boar", answer: "Kahtoo Pundree" },
    { category: "Animals", word: "Bear", answer: "Karradee" },
    { category: "Animals", word: "Porcupine", answer: "Mullam Pundree" },
    { category: "Animals", word: "Snake", answer: "Paambu" },
    { category: "Animals", word: "Frog", answer: "Thavuhlei" },
    { category: "Animals", word: "Snail", answer: "Nutthei" },
    { category: "Animals", word: "Crocodile", answer: "Muthalei" },
    { category: "Animals", word: "Turtle", answer: "Armay" },
    //Birds category
    { category: "Birds", word: "Bird", answer: "Parravei" },
    { category: "Birds", word: "Cockerel", answer: "Sirvel" },
    { category: "Birds", word: "Duck", answer: "Vahtu/Thaara" },
    { category: "Birds", word: "Crow", answer: "Carhum" },
    { category: "Birds", word: "Pigeon", answer: "Purah" },
    { category: "Birds", word: "Seagull", answer: "Kaddul Parravei" },
    { category: "Birds", word: "Peacock", answer: "Myill" },
    { category: "Birds", word: "Sparrow", answer: "Kuruvee" },
    { category: "Birds", word: "Parrot", answer: "Killee" },
    { category: "Birds", word: "Eagle", answer: "Parundoo" },
    { category: "Birds", word: "Vulture", answer: "Caluhoo" },
    { category: "Birds", word: "Chicken", answer: "Cawlee" },
    { category: "Birds", word: "Woodpecker", answer: "Maram cothi Parravei" },
    { category: "Birds", word: "Swan", answer: "Annam" },
    { category: "Birds", word: "Crane", answer: "Cockoo" },
    { category: "Birds", word: "Mud bird", answer: "Seroo Parravei" },
    //Insects and Reptiles category
    { category: "Insects and Reptiles", word: "Lizard", answer: "Palee" },
    { category: "Insects and Reptiles", word: "Beetle", answer: "Vandu" },
    { category: "Insects and Reptiles", word: "Ant", answer: "Errumbu" },
    { category: "Insects and Reptiles", word: "Ladybird", answer: "Vandu" },
    { category: "Insects and Reptiles", word: "Frog", answer: "Thavalei" },
    { category: "Insects and Reptiles", word: "Bee", answer: "Theinee" },
    { category: "Insects and Reptiles", word: "Wasp", answer: "Cullavee" },
    { category: "Insects and Reptiles", word: "Fly", answer: "Cawsoo, illayaan, ee" },
    { category: "Insects and Reptiles", word: "Mosquito", answer: "Nulumbu" },
    { category: "Insects and Reptiles", word: "Cockroach", answer: "Carrapaan pootchee" },
    { category: "Insects and Reptiles", word: "Snail", answer: "Nathei" },
    { category: "Insects and Reptiles", word: "Slug", answer: "Karru vandu, marra utei, ill-lay uttei" },
    { category: "Insects and Reptiles", word: "Leech", answer: "Uttei" },
    { category: "Insects and Reptiles", word: "Scorpion", answer: "Thurl" },
    { category: "Insects and Reptiles", word: "Gecko", answer: "Putchawndi" },
    { category: "Insects and Reptiles", word: "Spider", answer: "Silundi" },
    { category: "Insects and Reptiles", word: "Tick", answer: "Thuloo" },
    { category: "Insects and Reptiles", word: "Centipede", answer: "Mutta Thurl, Pooraan" },
    { category: "Insects and Reptiles", word: "Worm", answer: "Pull-loo" },
    { category: "Insects and Reptiles", word: "Monitor lizard", answer: "Udumboo" },
    { category: "Insects and Reptiles", word: "Butterfly", answer: "Van Natthu Pootchee" },
    { category: "Insects and Reptiles", word: "Caterpillar", answer: "Cumbalee Pootche" },
    { category: "Insects and Reptiles", word: "Dragonfly", answer: "Thoombee" },
    //Nouns category
    { category: "Nouns", word: "Comb", answer: "Seepu" },
    { category: "Nouns", word: "Box", answer: "Petti" },
    { category: "Nouns", word: "Stone", answer: "Kal" },
    { category: "Nouns", word: "Chair", answer: "Kahtheeray" },
    { category: "Nouns", word: "Tooth", answer: "Pal" },
    { category: "Nouns", word: "Word", answer: "Sol" },
    { category: "Nouns", word: "Grass", answer: "Pul" },
    { category: "Nouns", word: "Bow", answer: "Vil" },
    { category: "Nouns", word: "Table", answer: "Maysay" },
    { category: "Nouns", word: "Bed", answer: "Kattil" },
    { category: "Nouns", word: "Window", answer: "Yannul" },
    { category: "Nouns", word: "Flower", answer: "Poo" },
    { category: "Nouns", word: "Door", answer: "Kathavu" },
    { category: "Nouns", word: "Leaf", answer: "illay" },
    { category: "Nouns", word: "Cold drink", answer: "Coolir pahnam" },
    { category: "Nouns", word: "Lid", answer: "Moodi" },
    { category: "Nouns", word: "Water", answer: "Thanee" },
    { category: "Nouns", word: "Cap", answer: "Thoppee" },
    { category: "Nouns", word: "Paper", answer: "Kadathasee" },
    { category: "Nouns", word: "Bottle", answer: "Porthul" },
    { category: "Nouns", word: "Plug", answer: "Min Inaippu Saathanam" },
    { category: "Nouns", word: "Pillow", answer: "Thalani" },
    { category: "Nouns", word: "Coat", answer: "Maylan-gee" },
    { category: "Nouns", word: "Ball", answer: "Pundoo" },
    { category: "Nouns", word: "Bat", answer: "Muttei" },
    { category: "Nouns", word: "Bag", answer: "Pie" },
    { category: "Nouns", word: "Book", answer: "Putaham" },
    { category: "Nouns", word: "Tree", answer: "Maram" },
    { category: "Nouns", word: "Mat/rug", answer: "Paai" },
    { category: "Nouns", word: "Rain", answer: "Mullei" },
    { category: "Nouns", word: "Sea/Ocean", answer: "Kuddal" },
    { category: "Nouns", word: "Road", answer: "Paathei" },
    { category: "Nouns", word: "Lane", answer: "Olungei" }
  ];
  
  
